// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3RkPx9axre5IzJVn9vsmrhCqpVbjxio',
    appId: '1:668823680278:web:b4163bfb13bb70455e0c37',
    messagingSenderId: '668823680278',
    projectId: 'tour-ci',
    authDomain: 'tour-ci.firebaseapp.com',
    storageBucket: 'tour-ci.appspot.com',
    measurementId: 'G-HEGHPWLPNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5Xm4OwGrjrE_7ZZ8yeEcwBetLJwkceM',
    appId: '1:668823680278:android:735b99ace6a738af5e0c37',
    messagingSenderId: '668823680278',
    projectId: 'tour-ci',
    storageBucket: 'tour-ci.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclQxTFGQlbUPF_U3pXsL_3uT4fcoCmpQ',
    appId: '1:668823680278:ios:858f38e3b9fe9bf35e0c37',
    messagingSenderId: '668823680278',
    projectId: 'tour-ci',
    storageBucket: 'tour-ci.appspot.com',
    iosClientId: '668823680278-reqh1h478b93gvmn4hv4djmpcp162nct.apps.googleusercontent.com',
    iosBundleId: 'com.reinvent.tourCi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCclQxTFGQlbUPF_U3pXsL_3uT4fcoCmpQ',
    appId: '1:668823680278:ios:858f38e3b9fe9bf35e0c37',
    messagingSenderId: '668823680278',
    projectId: 'tour-ci',
    storageBucket: 'tour-ci.appspot.com',
    iosClientId: '668823680278-reqh1h478b93gvmn4hv4djmpcp162nct.apps.googleusercontent.com',
    iosBundleId: 'com.reinvent.tourCi',
  );
}
